import assert from 'node:assert'
import { readFileSync } from 'node:fs'
import { compile } from 'json-schema-to-typescript'

let pass = 0, fail = 0
async function t(name: string, fn: () => void | Promise<void>) {
  try { await fn(); pass++; console.log('  ok   ' + name) }
  catch (e) { fail++; console.log('  FAIL ' + name + '\n       ' + (e as Error).stack) }
}

const GENERATED_BANNER = `/**
 * This file was automatically generated by \`pnpm generate-types\` from
 * schema/attestation.schema.json. Do not edit this file directly — edit the
 * schema and regenerate, or your change will be silently overwritten (and,
 * per the test in generated-types-freshness.test.ts, CI will reject it).
 */`

console.log('generated-types.ts：与 schema/attestation.schema.json 是同一份来源生成的')

await t('重新生成 与 已提交的 src/generated-types.ts 逐字节一致（防止手改 schema 忘了重新生成类型）', async () => {
  const schema = JSON.parse(readFileSync(new URL('../schema/attestation.schema.json', import.meta.url), 'utf8'))
  const fresh = await compile(schema, 'AttestationPayload', {
    additionalProperties: false,
    bannerComment: GENERATED_BANNER,
    customName: (schema, keyNameFromDefinition) =>
      schema.$id === 'https://mcpcheckup.com/schema/attestation-payload-v0.3.json' ? 'AttestationPayload' : undefined,
  })
  const committed = readFileSync(new URL('./generated-types.ts', import.meta.url), 'utf8')
  // Normalize CRLF -> LF before comparing: `compile()` always emits LF, but a
  // fresh git checkout on a machine with core.autocrlf=true rewrites the
  // committed file to CRLF on disk. That's a checkout artifact, not content
  // drift, so it must not fail this test.
  assert.equal(
    fresh.replace(/\r\n/g, '\n'),
    committed.replace(/\r\n/g, '\n'),
    'src/generated-types.ts 已经和 schema 不同步了——改完 schema/attestation.schema.json 之后要跑 `pnpm generate-types` 并把结果一起提交',
  )
})

console.log(`\n${pass} passed, ${fail} failed`)
process.exitCode = fail ? 1 : 0
