// 从 schema/attestation.schema.json 生成 src/generated-types.ts。
// 类型与 schema 必须是同一份来源——改完 schema 记得跑这个脚本，
// generated-types-freshness.test.ts 会在忘记时挂掉。
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { compile } from 'json-schema-to-typescript'

const schemaPath = fileURLToPath(new URL('../schema/attestation.schema.json', import.meta.url))
const outPath = fileURLToPath(new URL('../src/generated-types.ts', import.meta.url))

const GENERATED_BANNER = `/**
 * This file was automatically generated by \`pnpm generate-types\` from
 * schema/attestation.schema.json. Do not edit this file directly — edit the
 * schema and regenerate, or your change will be silently overwritten (and,
 * per the test in generated-types-freshness.test.ts, CI will reject it).
 */`

const schema = JSON.parse(readFileSync(schemaPath, 'utf8'))
const ts = await compile(schema, 'AttestationPayload', {
  additionalProperties: false,
  bannerComment: GENERATED_BANNER,
  // json-schema-to-typescript names the root type from schema.title || schema.$id
  // before it ever looks at the name argument above. The schema deliberately has
  // no title (so $defs' own titles read cleanly) and a real $id (so it's still a
  // properly identified JSON Schema) — so the root type specifically needs this
  // override, or it would come out named after the $id URL.
  customName: (schema, keyNameFromDefinition) =>
    schema.$id === 'https://mcpcheckup.com/schema/attestation-payload-v0.3.json' ? 'AttestationPayload' : undefined,
})

writeFileSync(outPath, ts)
console.log(`wrote ${outPath}`)
